theme: jekyll-theme-minimal  
title: Shashwat Bajaj's homepage  
description: Bookmark this to keep an eye on the project's updates!  

** World Bank Open Data
The WB Open Data set contains a vast international collection of data & analytics for promotion of development.  

You may access the Data Set [here](https://data.worldbank.org).  

*** Applications of WB Open Data
Some potentail applications':'
- Economic Development Analysis':'
  * Compare GDP with different factors.
- Education Stats':'
  * Gather & analyze enrollment information or stats based on region.
- Climate Analysis':'
  * Record Carbon Dioxide emissions across a specific usage pattern.
